# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  NES_config = debug
endif
ifeq ($(config),release)
  NES_config = release
endif
ifeq ($(config),dist)
  NES_config = dist
endif

PROJECTS := NES

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

NES:
ifneq (,$(NES_config))
	@echo "==== Building NES ($(NES_config)) ===="
	@${MAKE} --no-print-directory -C NES -f Makefile config=$(NES_config)
endif

clean:
	@${MAKE} --no-print-directory -C NES -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   NES"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"